# Generated by Django 5.1.4 on 2025-01-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='profile_imgs/'),
            preserve_default=False,
        ),
    ]
