# Generated by Django 5.1.4 on 2025-01-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_imgs/default_user.png', upload_to='profile_imgs/'),
        ),
    ]
